In [3]:
import scanpy as sc

print("Scanpy imported successfully")
print(sc.AnnData)

Scanpy imported successfully
<class 'anndata._core.anndata.AnnData'>

In [5]:
data_path = "../data/GSE201348/GSM606145/"

adata = sc.read_10x_mtx(
    data_path,
    var_names="gene_symbols",
    make_unique=True
)

print(adata)

AnnData object with n_obs × n_vars = 1651 × 33538
    var: 'gene_ids', 'feature_types'

In [6]:
adata.obs.head()

Empty DataFrame
Columns: []
Index: [AAACCCAAGTTATGGA-1, AAACCCACAACGCCCA-1, AAACCCAGTCAGTCCG-1, AAACGAAGTTGGTGTT-1, AAACGCTAGGAGCAAA-1]

In [7]:
print(adata.obs.index[:5])

Index(['AAACCCAAGTTATGGA-1', 'AAACCCACAACGCCCA-1', 'AAACCCAGTCAGTCCG-1',
       'AAACGAAGTTGGTGTT-1', 'AAACGCTAGGAGCAAA-1'],
      dtype='object')

In [8]:
print(adata.obs.columns)

Index([], dtype='object')

In [10]:
adata.var.head()

                    gene_ids    feature_types
MIR1302-2HG  ENSG00000243485  Gene Expression
FAM138A      ENSG00000237613  Gene Expression
OR4F5        ENSG00000186092  Gene Expression
AL627309.1   ENSG00000238009  Gene Expression
AL627309.3   ENSG00000239945  Gene Expression

In [11]:
print(adata.X.shape)

(1651, 33538)

In [12]:
print(type(adata.X))

<class 'scipy.sparse._csc.csc_matrix'>